model_args:
  use_seg: true
  hist_channels: 32
  init_method: Normal
  CTN_enc_hidden_list: [32, 64, 128, 256, 256]
  CTN_dec_hidden_list: [256, 128, 64, 32, 32]
  HEN_hidden: 32

optimizer_args:
  loss_lambda1: 1.5
  loss_lambda2: 0.5
  learning_rate: 0.00005
  beta1: 0.5
  beta2: 0.999

trainer_args:
  accelerator: gpu
  devices: 1
  max_epochs: 200
  precision: 16 # 32 or 16
  ckpt_dir: output/lightning_ckpt

dataset_args:
  raw_dir: data/raw

  img_dim: [128, 128]
  l_bin: 8
  ab_bin: 64
  num_classes: 150

  batch_size: 6
  num_workers: 8
