model_args:
  use_seg: true
  hist_channels: 64
  init_method: Normal
  CTN_enc_hidden_list: [64, 64]
  CTN_dec_hidden_list: [64, 64]
  HEN_hidden: 32

optimizer_args:
  loss_lambda1: 1.5
  loss_lambda2: 0.5
  learning_rate: 0.00005
  beta1: 0.5
  beta2: 0.999

trainer_args:
  accelerator: cpu
  devices: 1
  max_epochs: 200
  precision: 16 # 32 or 16
  ckpt_dir: output/lightning_ckpt

dataset_args:
  raw_dir: data/raw
  processed_dir: data/processed

  resize_dim: [512, 512]
  l_bin: 64
  ab_bin: 64
  num_classes: 50

  batch_size: 2
  num_workers: 8
