model_args:
  use_seg: true
  hist_channels: 64
  init_method: Normal
  encoder_name: mobilenetv3_small_100
  CTN_enc_hidden_list: [16, 16, 24, 48, 576]
  CTN_dec_hidden_list: [576, 48, 48, 64, 64]
  HEN_hidden: 128

optimizer_args:
  loss_lambda0: 0.5
  loss_lambda1: 10 # 1.5
  loss_lambda2: 10
  learning_rate: 0.0002
  beta1: 0.5
  beta2: 0.999

trainer_args:
  accelerator: gpu
  devices: 7
  max_epochs: 100
  precision: 16 # 32 or 16
  ckpt_dir: output/MobileNetV3Distill

dataset_args:
  raw_dir: data/raw

  img_dim: [256, 256]
  l_bin: 8
  ab_bin: 64
  num_classes: 150

  batch_size: 8
  num_workers: 8
